<?php
/**
 * Created by PhpStorm.
 * User: miaomin
 * Date: 7/18/2017
 * Time: 16:37
 */

namespace app\api\controller;
// 注意首字母大小写问题
use think\Controller;

class AdminUser extends Controller
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub

        echo 'Init start...';
    }

    public function index(){
        return 'OOO';
    }

    public function adminUserInfo($id){
        return model('base/AdminUser')->find($id);
    }

    public function _empty(){
        return 'Empty';
    }
}